apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: project2
        image: saneeshshruthi/project2
        ports:
        - containerPort: 80
